# Generated by Django 5.2.14 on 2026-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('public_repos', models.PositiveIntegerField(default=0)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
